package OPTI.vcs;

/*Generated by MPS */

import jetbrains.mps.vcs.mergehints.runtime.VCSAspectDescriptor;
import jetbrains.mps.vcs.mergehints.runtime.VCSConceptAspect;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class VCSDescriptor extends VCSAspectDescriptor.BaseVcsAspectDescriptor {
  public VCSDescriptor() {
  }

  @Override
  public VCSConceptAspect getVCSDescriptor(SAbstractConcept c) {
    SAbstractConcept cncpt = c;
    return null;
  }
}
