package OPTI.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum HARD_TYPE {
  PC("PC", 0),
  RASPY("RASPY", 1),
  PHONE("PHONE", 2),
  NAS("NAS", 3);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final int myValue;
  HARD_TYPE(String name, int value) {
    myName = name;
    myValue = value;
  }
  public int getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Integer.toString(myValue);
  }
  public static List<HARD_TYPE> getConstants() {
    List<HARD_TYPE> list = ListSequence.fromList(new LinkedList<HARD_TYPE>());
    ListSequence.fromList(list).addElement(HARD_TYPE.PC);
    ListSequence.fromList(list).addElement(HARD_TYPE.RASPY);
    ListSequence.fromList(list).addElement(HARD_TYPE.PHONE);
    ListSequence.fromList(list).addElement(HARD_TYPE.NAS);
    return list;
  }
  public static HARD_TYPE getDefault() {
    return HARD_TYPE.PC;
  }
  public static HARD_TYPE parseValue(String value) {
    if (value == null) {
      return HARD_TYPE.getDefault();
    }
    if (value.equals(HARD_TYPE.PC.getValueAsString())) {
      return HARD_TYPE.PC;
    }
    if (value.equals(HARD_TYPE.RASPY.getValueAsString())) {
      return HARD_TYPE.RASPY;
    }
    if (value.equals(HARD_TYPE.PHONE.getValueAsString())) {
      return HARD_TYPE.PHONE;
    }
    if (value.equals(HARD_TYPE.NAS.getValueAsString())) {
      return HARD_TYPE.NAS;
    }
    return HARD_TYPE.getDefault();
  }
}
