package OPTI.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;

public class IconContainer {
  protected static IconResource RESOURCE_a0a3a0a1b0d = new IconResource("TextIcon_1.png", IconContainer.class);
}
